name: ambroseconsulting
favicon: null
layout_spectrum: 0.45780827500857413
typography_spectrum: 0.17829419067129493
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5809042984619737
  lightness: 0.7139094402082264
  saturation: 0.7354424896184355
  rhythmicContrast: 0.9606581311672926
purpose: []
